// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var LitHtml = require("../src/LitHtml.bs.js");

LitHtml.html(( `My name is ${name}` ));

var name = "Jack";

exports.name = name;
/*  Not a pure module */
