// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';


var Element = /* module */[];

var DocumentFragment = /* module */[];

var Partial = /* module */[];

var RenderOptions = /* module */[];

var TemplateResult = /* module */[];

exports.Element = Element;
exports.DocumentFragment = DocumentFragment;
exports.Partial = Partial;
exports.RenderOptions = RenderOptions;
exports.TemplateResult = TemplateResult;
/* No side effect */
